### ISSUE TITLE
Implement Quote.jsx

### ISSUE THREAD

**Issue by ysh0305** [acm-ucr/robosub-website#17]
<img width="231" alt="image" src="https://github.com/acm-ucr/robosub-website/assets/123037099/3e1ef305-befc-4751-b96e-83cdddbc543b">
<img width="223" alt="image" src="https://github.com/acm-ucr/robosub-website/assets/123037099/6321b638-574b-4db2-a39d-6617247d11b9">
<img width="230" alt="image" src="https://github.com/acm-ucr/robosub-website/assets/123037099/e929a4ed-dec7-4d44-910a-3aca39d509ab">

Number of props: **2, _quote, person_**
Location: **Join Page**
Number of Images: **0**
React Icon: **No**
Other component use: **None**
Description: **This component should include a box with a gradient yellow border. In tailwind, there is no direct setting to apply a gradient to the border so you will need to create 2 boxes right on top of each other with one of them being gradient. Inside the box, it should include 1 quote followed by the person's name and year. The width of the quote box should be set (for example: w-1/3 or w-[30%],  and the height will vary based on the length of the quote.**

PATH: /src/components/join/Quote.jsx

**Comment by mogunwusi** [comment]
![Screen Shot 2024-01-18 at 8 54 19 PM](https://github.com/acm-ucr/robosub-website/assets/152947563/d11eb476-7f4f-46ba-bcba-509acec4bebc)
