### ISSUE TITLE
Implement Board.jsx

### ISSUE THREAD

**Issue by ysh0305** [acm-ucr/robosub-website#19]
<img width="112" alt="image" src="https://github.com/acm-ucr/robosub-website/assets/123037099/ba7b888e-5b69-4627-9465-af4f1a234707">

Number of props: **3, _image, name, role_**
Location: **Boards Page**
Number of Images: **1 (only for tesing) cat.png**
React Icon: **No**
Other component use: **None**
Description: **The component includes an image, name, role, and a gradient border. To create a gradient border, you will first create a circle with blue gradient and then put the image in the center.**

Path: **/src/components/board/Board.jsx**

[Example](https://github.com/acm-ucr/asme-website/blob/dev/src/components/board/Board.jsx)

**Comment by swedenagu** [comment]
<img width="843" alt="Screenshot 2024-01-13 at 12 26 04 AM" src="https://github.com/acm-ucr/robosub-website/assets/84001329/16d4e3d4-dd80-4a35-b180-e6691949d19f">
<img width="310" alt="Screenshot 2024-01-13 at 12 26 48 AM" src="https://github.com/acm-ucr/robosub-website/assets/84001329/b723a335-1835-4a1b-b128-35bb9bbc64e8">
